### ISSUE TITLE
Answer: Why is the game not just played on 1 board?

### ISSUE THREAD

**Issue by PeachTreeOath** [PeachTreeOath/LD39#36]

**Comment by PeachTreeOath** [comment]
We already have the gameplay aspect of desyncing the boards and that's good. Is there more we can do?

**Comment by grollapps** [comment]
There was talk about prestige increasing stats of a single board, this gives a twist on "powerup" choices

**Comment by MrChro** [comment]
There will be one board (relationship) that is our primary win/loss function.  The relationship board is directly effected by the resource (money) and progress (Education) boards.  Those two boards are dependent on the duration (HP) board.
