### ISSUE TITLE
Design deep dive: Job board

### ISSUE THREAD

**Issue by PeachTreeOath** [PeachTreeOath/LD39#38]

**Comment by PeachTreeOath** [comment]
See if there's any way to flesh out / refine / add to the board to create more interesting decisions.

Currently the board constantly populates with cash drops. Perhaps this would be the board we could introduce an anti-cash negative mechanic?

**Comment by mjeffery** [comment]
What determines the initial drop pattern of the board?  What  determines the "size" of the cash drops?
