### ISSUE TITLE
Answer: What does this game have to do with the theme?

### ISSUE THREAD

**Issue by PeachTreeOath** [PeachTreeOath/LD39#43]

**Comment by PeachTreeOath** [comment]
Figure out all the UI elements and lore that will convince people their character or legacy/family is Running Out of Power.

**Comment by MrChro** [comment]
It will be a time based game where you're running out of moves constantly.  We'll have the feel of "losing power" by having a time bar slowly fall down as well as an aging picture of a man showing you're how old you are.  The goal of the game is to progress as far as you can as you're constantly running low on time.
