### ISSUE TITLE
UI - Log needs to be beautified

### ISSUE THREAD

**Issue by PeachTreeOath** [PeachTreeOath/LD39#78]

**Comment by PeachTreeOath** [comment]
See the lower right part of https://media.discordapp.net/attachments/217458074506493953/341099977642344449/Capture.PNG?width=704&height=443

**Comment by PeachTreeOath** [comment]
Be more specific with text too (super potion picked up - gain 10 to max age) etc

**Comment by grollapps** [comment]
Worst task ever
